name: CustomBoss
version: '1.0-SNAPSHOT'
main: com.savage.plugins.customboss.CustomBoss
api-version: 1.19
authors: [ SavageDev ]
commands:
  createboss:
    description: Creates a custom boss based on command args
    aliases: cboss
    usage: /createboss [mob] [name] [health] [damage]

